js:
  dmJCarouselLiteBehaviorPlugin:
    jcarousellite:  jquery.jcarousel-lite.modified.pack.min
    mousewheel:     jquery.mousewheel.min
    launch: dmJCarouselLiteBehavior.pack.min
    form: form/dmJCarouselLiteBehaviorForm
css:
  dmJCarouselLiteBehaviorPlugin:
    default: default